# travis git repo-cloning settings
git:
  # clone repo to depth of n commits
  depth: 3
  # clone with quiet flag
  quiet: false
  # clone submodules
  submodules: true

# whitelist travis build branches with "only", blacklist with "except"
branches:
  only:
  - master
  - devel

# supporting toolchain for builds
language: cpp

# build environments
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - cmake
          - libboost-all-dev
          - gcc-8
          - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        sources:
          - llvm-toolchain-xenial-7
        apt:
          packages:
          - cmake
          - libboost-all-dev
          - clang-7
          - clang-tools-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"


# build / test cmds
script:
  - cd tests
  - ./test_runner.sh

